name: Build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - main

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: '3.9'
        - run: |
            pip install wheel
            python setup.py sdist bdist_wheel
        - uses: actions/upload-artifact@v2
          with:
            name: dist
            path: dist/
