name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: |
          pip install wheel
          python setup.py sdist bdist_wheel
      - uses: pypa/gh-action-pypi-publish@v1.4.1
          with:
            user: __token__
            password: ${{ secrets.TESTPYPI_PASSWORD }}
            repository_url: https://test.pypi.org/legacy/
      - uses: pypa/gh-action-pypi-publish@v1.4.1
          with:
            user: __token__
            password: ${{ secrets.PYPI_PASSWORD }}
      - name: Create Release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            draft: false
            prerelease: false
